# Generated by Django 4.2.3 on 2023-07-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='productos', verbose_name='imagen')),
                ('titulo', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=40, verbose_name='Descripcion')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
        ),
        migrations.DeleteModel(
            name='project',
        ),
    ]
