# Generated by Django 4.2.2 on 2023-06-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_producto_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=40, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(default='', upload_to='productos', verbose_name='imagen'),
        ),
    ]
