# Generated by Django 4.2.3 on 2023-07-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_rename_email_contacto_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creacion'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Usuario'),
        ),
    ]
